# Indexing in Python is a way to refer the individual items within an iterable
# by its position.In other words, you can directly access your elements of 
# choice within an iterable and do various operations depending on your needs. 
# In Python, objects are “zero-indexed” meaning the position count starts at zero.

# Index() is an inbuilt function in Python, which searches for a given element 
# from the start of the list and returns the lowest index where the element appears.
# element – The element whose lowest index will be returned. start (Optional) 
# The position from where the search begins. 

# The negative indexing is the act of indexing from the end of the 
# list with indexing starting at -1 i.e. -1 gives the last element of list,
# -2 gives the second last element of list and so on.