user=int(input("enter no: "))
# b=str(user)
# c=""
# i=-1
# while i>=-len(b):
#     c=c+b[i]
#     i=i-1
# print(c)

# num=int(input("enter no"))
# n=str(num)
# s=""
# i=1
# while i<=len(n):
#     a=n[-i]
#     s=s+a
#     i=i-1
# print(int(s))

# u1=input("enter name:")
# u2=input("enter name:")
# u3=input("enter name:")
# i=0
# d=" "
# while i<len(u1) and i<len(u2):
#     if u1[i]==u1[0] and u2[i]==u2[0]:
#         cap=u1[i].upper()
#         cap1=u2[i].upper()
#         d+=cap+"."+cap1
#     i=i+1
# print(d+"."+u3)



# u1=input("enter name: ")
# u2=input("enter name: ")
# u3=input("enter name: ")
# i=0
# k=" "
# while i<len(u1) and i<len(u2) and i<len(u3):
#     if u1[i]==u1[0] and u2[i]==u2[0] and u3[i]==u3[0]:
#         cap=u1[i].upper()
#         cap2=u2[i].upper()
#         cap3=u3[i].upper()
#         k=k+cap+"."+cap2+"."+cap3
#     i=i+1
# print(k)