# win=[987,"apple",9.0,5678,9876.0,"sothingnao"]
# i=0
# k=[]
# n=[]
# l=[]
# while i<len(win):
#     if (type(win[i])==int):
#         k.append(win[i])
#     elif (type(win[i])==float):
#         n.append(win[i])
#     # elif (type(win[i])==str):
#     else:
#         l.append(win[i])
#     i=i+1
# print(k,"is integer")
# print(n,"is float")
# print(l,"is string")

# a=[[1,2],[5,8],[4,7],[3,9]] 
# i=0
# b=[]
# while i<len(a[i]):
#     if a[i]%2==0:
#         b.append(a[i])
#     i=i+1
# print(b)


# a=[[7,9],[9,8,7],[9,5,2],[66,12]]


# a=[9,-8,9.7,7,6,-5,-4,5.66,8.5,15,-5]
# i=0
# n=[]
# b=[]
# h=[]
# while i<len(a):
#     if (type(a[i])==float):
#         n.append(a[i])
#     elif a[i]<0:
#         b.append(a[i])
#     else:
#         h.append(a[i])
#     i=i+1
# print(n,"\n",b,"\n",h)