# a=['678']
# i=0
# while i<len(a):
#     j=0
#     while j<len(a[i]):
#         c=int(a[i][j])*int(a[i][j])
#         print(c)
#         j=j+1
#     i=i+1
    


# a=['432']
# i=0
# while i<len(a):   
#     j=0
#     while j<len(a[i]):
#         print(a[i][j])
#         # print(a[0][0])
#         break
#         j=j+1
#     i=i+1
    

# a=['432']
# i=0
# while i<len(a):
#     j=0
#     while j<len(a[i]):
#         print(a[i][j])
#         j=j+1
#     i=i+1

# a=['567']
# i=0
# while i<len(a):
#     j=0
#     while j<len(a[i]):
#         ans=int(a[i][j])*int(a[i][j])
#         print(ans)
#         j=j+1
#     i=i+1