# m=['M', 'y..','M','e','n','t','o','r..','I','s..','M','o','n','i!']
# i=0
# s=" "
# while  i<len(m):
#     j=0
#     while j<len(m[i]):
#         s=s+m[i][j]
#         j=j+1
#     i=i+1
# print(s)

# m=[9,8,7,6,5]
# i=0
# s=0
# a=[]
# while i<len(m):
#     j=0
#     while j<len(m[i]):
#         s+=m[i][j]
#         a.append(s)
#         j=j+1
#     i=i+1
# print(a)


# a=["p","r","e","e","t","y"]
# i=0
# s=" "
# while i<len(a):
#     j=0
#     while j<len(a[i]):
#         s=s+a[i][j]
#         j=j+1
#     i=i+1
# print(s)


# m='aabbbccccdddd'
# i=0
# a=[]
# while i<len(m):
#     if m[i] not in a:
#         a.append(m[i])
#     i=i+1
# print(a)


# o/p=['a','b','c','a','d']
# m='aabbbccccaaadddd'
# i=0
# a=[]
# while i<len(m):
#     if m[i] not in a:
#         a.append(m[i])
#     i=i+1
# print(a)

a=['a','s','h','w','i','n','i']
i=0
s=''
while i<len(a):
    j=0
    while j<len(a[i]):
        s+=a[i][j] 
        j=j+1
    i=i+1
print(s)