# o/p=MyMentorIsMoni
# m=['M', 'y','M','e','n','t','o','r','I','s','M','o','n','i']
# i=0
# s=" "
# while  i<len(m):
#     j=0
#     while j<len(m[i]):
#         s=s+m[i][j]
#         j=j+1
#     i=i+1
# print(s)

#o/p=["m","o","n","i","s","o","o"]
# a=["monnisoo"]
# i=0
# p=[]
# while i <len(a):
#     j=0
#     while j<len(a[i]):
#         p.append(a[i][j])
#         j=j+1
#     i=i+1

# print(p)


a=["akoney"]
i=0
p=[]
while i<len(a):
    j=0
    while j<len(a[i]):
        p.append(a[i][j])
        j=j+1
    i=i+1
print(p)